data:
  dataset_dir: "${task.dataset_dir}"
  train_split: 0.8
  batch_size_train: 64
  batch_size_val: 64
  num_workers_batch: 16
  prefetch_factor: 4
  balance_trust_levels: true

augmentation:
  enabled: True
  interpolation: "bilinear"
  size: [224, 224]
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

  cameras:
    wrist_rgb:
      enabled: True
      augmentations:
        RandomBrightnessContrast:
          brightness_limit: [0.7, 1.3]
          contrast_limit: [0.7, 1.3]
          p: 0.5
        GaussianBlur:
          blur_limit: [3, 7]
          sigma_limit: [0.1, 2.0]
          p: 0.4
        Affine:
          scale: [0.9, 1.1]
          translate_percent: [0.0, 0.1]
          rotate: [-10, 10]
          p: 0.4
        HueSaturationValue:
          hue_shift_limit: 0.1
          sat_shift_limit: 0.1
          val_shift_limit: 0.1
          p: 0.3
        Rotate:
          limit: [-10, 10]
          p: 0.3

    base_rgb:
      enabled: True
      augmentations:
        RandomBrightnessContrast:
          brightness_limit: [0.7, 1.3]
          contrast_limit: [0.7, 1.3]
          p: 0.5
        GaussianBlur:
          blur_limit: [3, 7]
          sigma_limit: [0.1, 2.0]
          p: 0.4
        Affine:
          scale: [0.9, 1.1]
          translate_percent: [0.0, 0.1]
          rotate: [-10, 10]
          p: 0.4
        HueSaturationValue:
          hue_shift_limit: 0.1
          sat_shift_limit: 0.1
          val_shift_limit: 0.1
          p: 0.3
